### ISSUE TITLE
Design contribution proposal

### ISSUE THREAD

**Issue by ihtiht** [rust-keylock/rust-keylock-lib#3]
Hi, I'm a designer. I contribute to open source projects. I would also like to contribute to rust-keylock. Do you need a design? I can design a logo for you.

 I'm waiting for your feedback...

**Comment by astonbitecode** [comment]
Hi, thank you that you are willing to contribute.
The truth is that until now the project focused more in the security and technical aspects and this is why it currently lacks in usability and UI.

The logo can be a good start.

**Comment by astonbitecode** [comment]
@ihtiht any updates on this?

**Comment by astonbitecode** [comment]
So I believe I should close this. If you are still interested, feel free to reopen.
